Подогнал под пп, сделано все кроме поиска и img дрелей
htmlacademy-htmlcss/1575237-technomart-29 pull request #13
Opened 2020-10-13 00:42 UTC by Imonahorse

2020-10-14 06:29 UTC, Shramkoweb requested changes

2020-10-14 06:29 UTC, Shramkoweb commented on css/style.css
> +
Лишний отступ

2020-10-14 06:29 UTC, Shramkoweb commented on css/style.css
> +  vertical-align: center;
`  vertical-align: center;` - не работает =)

2020-10-14 06:29 UTC, Shramkoweb commented on css/style.css
> +.brands-item:nth-child(2),
Добавь на каждый brands-item еще класс brands-item-имя-фирмы и тогда будет лучше.

Так как твой вариант очень хрупкий, при изменении ихпорядка фирм все сломается

2020-10-14 06:29 UTC, Shramkoweb commented on css/style.css
> +  font-family: "PT Sans", "Arial", sans-serif;
Ты же не просто везде вставлял шрифт? А только там где он не наследуется от родителя?

2020-10-14 18:45 UTC, Imonahorse commented on css/style.css
> +
Убрал все

2020-10-14 18:46 UTC, Imonahorse commented on css/style.css
> +  vertical-align: center;
Убрал

2020-10-14 18:48 UTC, Imonahorse commented on css/style.css
> +  font-family: "PT Sans", "Arial", sans-serif;
Там два шрифта, пт санс и Cuprum. Cuprum задан всей странице по умолчанию и inherit для форм и ссылок, а PT Sans указан отдельно в редких местах где он нужен. Норм ?

2020-10-14 18:51 UTC, Imonahorse commented on css/style.css
> +.brands-item:nth-child(2),
+

2020-10-15 06:48 UTC, Shramkoweb commented on css/style.css
> +  font-family: "PT Sans", "Arial", sans-serif;
Да, так ок

2020-10-16 07:59 UTC, Shramkoweb approved these changes

2020-10-16 07:59 UTC, merged