Закончил доступность для главной
htmlacademy-htmlcss/1575237-technomart-29 pull request #15
Opened 2020-10-19 20:34 UTC by Imonahorse

2020-10-20 18:52 UTC, Shramkoweb requested changes

2020-10-20 18:52 UTC, Shramkoweb commented on css/style.css
> +.search-input:hover+svg {
Пробелы между +

2020-10-20 18:52 UTC, Shramkoweb commented on css/style.css
> +  content: "";
Тут точно нужен контент?)

2020-10-20 18:52 UTC, Shramkoweb commented on css/style.css
> +.card-image-wrapper:focus+.card-buy-menu {
Пробелы между +

2020-10-20 18:52 UTC, Shramkoweb commented on css/style.css
> +
??

2020-10-20 18:52 UTC, Shramkoweb commented on index.html
> +                  <img class="card-image" src="./img/bosch-bfg-3000.png" width="184" height="164" alt="">
Пропал альт у картинки

2020-10-20 18:52 UTC, Shramkoweb commented on index.html
> +                  <img class="card-image" src="./img/bosch-bfg-6000.png" width="127" height="112" alt="">
Что-то с альтами случилось)

2020-10-20 18:52 UTC, Shramkoweb commented on index.html
> +                <img class="brands-picture" src="./img/aeg.png" width="151" height="96" alt="Фирма Aeg">
alt="Логотип фирмы Aeg"

2020-10-20 19:11 UTC, Imonahorse commented on index.html
> +                  <img class="card-image" src="./img/bosch-bfg-6000.png" width="127" height="112" alt="">
А зачем они нужны если они повторяют заголовок? В уроке по доступности Вадим говорил, что если в заголовке тоже самое что и в описании- проговаривать дважды смысла нет. Я и убрал.

2020-10-20 19:14 UTC, Imonahorse commented on css/style.css
> +.card-image-wrapper:focus+.card-buy-menu {
Vscode при сохранении автоматом убирает пробелы, как пофиксить? :)

2020-10-22 07:56 UTC, Shramkoweb approved these changes

2020-10-22 07:56 UTC, merged