Добавил классы и style.css
htmlacademy-htmlcss/1575237-technomart-29 pull request #4
Opened 2020-09-17 09:51 UTC by Imonahorse

2020-09-17 15:52 UTC, Shramkoweb requested changes
Не писал везде, тебе нужно пройтись и поправить

- Одинаковые отступы между всеми селекторами
- Если ты пишешь несколько селекторов через запятую, то каждый идет на новой строчке.
- Пофиксить отступы между селектором и открывающей кавычкой

2020-09-17 15:52 UTC, Shramkoweb commented on css/style.css
> +  --basic-light-white: rgba(0, 0, 0, 0.0001)
Я бы добавил, что он transparent

2020-09-17 15:52 UTC, Shramkoweb commented on css/style.css
> +  font-family: Cuprum, Ariel, sans-serif;
Линтер не ругается, что шрифты не в кавычках?

2020-09-17 15:52 UTC, Shramkoweb commented on css/style.css
> +.page a {
Между селекторами отступ

2020-09-17 15:52 UTC, Shramkoweb commented on css/style.css
> +  box-sizing: border-box;
Это можно вынести на самый верхний уровень и применить для всего документа. Тогда у всех блоков будет единое и адекватное поводение боксовой модели.
А так у тебя разные блоки ведут себя по разному теперь.

`*, *::before, *::after { box-sizing: border-box; }
`

2020-09-17 15:52 UTC, Shramkoweb commented on css/style.css
> +.site-navigation a{
отступ после `а`

2020-09-17 15:52 UTC, Shramkoweb commented on css/style.css
> +
что за отступ такой большой?

2020-09-17 15:52 UTC, Shramkoweb commented on css/style.css
> +.basket-link:active, .header-bookmark:active {
`.header-bookmark:active` на новую строчку перенеси

2020-09-17 15:52 UTC, Shramkoweb commented on css/style.css
> +
отступ лишний

2020-09-17 15:52 UTC, Shramkoweb commented on css/style.css
> +.offer-slider-item{
забыл отсуп

2020-09-17 15:52 UTC, Shramkoweb commented on css/style.css
> +}
можно обьединить

2020-09-17 15:52 UTC, Shramkoweb commented on css/style.css
> +.bestsellers-list, .brands-list {
каждый селектор на новой строчке

2020-09-17 15:52 UTC, Shramkoweb commented on css/style.css
> +  font-family: "PT Sans", sans-serif;
А тут все таки шрифт уже в каввычках

2020-09-17 15:52 UTC, Shramkoweb commented on css/style.css
> +box-shadow: inset 0px -5px 0px rgba(0, 0, 0, 0.24);
поехало

2020-09-17 15:52 UTC, Shramkoweb commented on index.html
> +<html class="page" lang="ru">
А что с версткой произошло?)

2020-09-17 16:25 UTC, Imonahorse commented on css/style.css
> +  --basic-light-white: rgba(0, 0, 0, 0.0001)
А надо на каждый rgba(0, 0, 0, 0,0000001), rgba(0, 0, 0, 0,0000002), rgba(0, 0, 0, 0,0000003) делать отдельный --basic-a little-darker-pink? Если я чтобы без этого обойдусь буду называть 50 оттенков белого серым зеленым и красным это не ошибка?

2020-09-17 16:25 UTC, Imonahorse commented on css/style.css
> +  font-family: Cuprum, Ariel, sans-serif;
У меня три плагина для исправления кода и не один не стал css исправлять=) Сегодня займусь.

2020-09-17 16:25 UTC, Imonahorse commented on css/style.css
> +.page a {
Аааа стоп ты под отступом понимаешь tab а не пробел?

2020-09-17 16:26 UTC, Imonahorse commented on css/style.css
> +  box-sizing: border-box;
Не понял если честно как это надо сделать.

2020-09-17 16:27 UTC, Imonahorse commented on index.html
> +<html class="page" lang="ru">
А что там произошло?

2020-09-17 17:33 UTC, Shramkoweb commented on css/style.css
> +  --basic-light-white: rgba(0, 0, 0, 0.0001)
Не ошибка. Это проблема проектов без дизайн системы =(

2020-09-17 17:34 UTC, Shramkoweb commented on css/style.css
> +.page a {
ну имеется ввиду пустая строчка между селекторами

2020-09-17 17:35 UTC, Shramkoweb commented on css/style.css
> +  box-sizing: border-box;
Просто добавь в самом начале css код который я написал. Таким образом у тебя все блоки будут box-sizing: border-box; и это удобно.
Сейчас же у тебя какой то блок такой, а другой с иной блочной моделью. Это может привести к ошибкам

2020-09-17 17:35 UTC, Shramkoweb commented on index.html
> +<html class="page" lang="ru">
НУ показывает, как будто ты там все переписал =)

2020-09-18 15:57 UTC, Shramkoweb approved these changes

2020-09-18 15:57 UTC, Shramkoweb commented on css/style.css
> +/* !!!!!Кастомные свойства */
!!!!! ?)

2020-09-18 15:57 UTC, merged