Проверочный
htmlacademy-htmlcss/1575237-technomart-29 pull request #9
Opened 2020-09-28 12:39 UTC by Imonahorse

2020-09-28 16:25 UTC, Shramkoweb requested changes

2020-09-28 16:25 UTC, Shramkoweb commented on catalog.html
> +              <a class="social-item social-item social-item-vkontakte" href="https://vk.com/">Вконтакте</a>
social-item - два раза продублировал

2020-09-28 16:25 UTC, Shramkoweb commented on catalog.html
> +              <a class="social-item social-item-instagram" href="https://www.instagram.com/?hl=ru">Инстаграм</a>
`?hl=ru` убрать в урле. Так как ты же не знаешь, вдруг америкенец зайдет на сайт твой =)

2020-09-28 16:25 UTC, Shramkoweb commented on css/style.css
> +  flex-direction: row;
flex-direction: row; по умолчанию можно не писать - я же тебе кидал статью =)

2020-09-28 16:25 UTC, Shramkoweb commented on css/style.css
>  }
Это прям нужно? Если нет, то удали

2020-10-01 06:14 UTC, Shramkoweb requested changes

2020-10-01 06:14 UTC, Shramkoweb commented on css/style.css
> +  …
??

2020-10-01 06:14 UTC, Shramkoweb commented on catalog.html
> +              <a class="social-item social-item-instagram" href="https://www.instagram.com/?hl=ru">Инстаграм</a>
Не убрал

2020-10-01 06:14 UTC, Shramkoweb commented on css/style.css
>  }
Нужен ответ

2020-10-01 06:14 UTC, Shramkoweb commented on css/style.css
> +.footer-main-menu {}
Пустой селлектор

2020-10-01 06:14 UTC, Shramkoweb commented on index.html
> +          <form action="" method="GET">
Добавь action - https://echo.htmlacademy.ru

2020-10-01 12:09 UTC, Imonahorse commented on css/style.css
>  }
удалил, оказалось ненужно

2020-10-01 12:09 UTC, Imonahorse commented on css/style.css
> +  flex-direction: row;
я знаю, забыл про него, удалено

2020-10-01 12:09 UTC, Imonahorse commented on catalog.html
> +              <a class="social-item social-item-instagram" href="https://www.instagram.com/?hl=ru">Инстаграм</a>
удалено

2020-10-01 12:09 UTC, Imonahorse commented on catalog.html
> +              <a class="social-item social-item social-item-vkontakte" href="https://vk.com/">Вконтакте</a>
удалено

2020-10-01 12:13 UTC, Imonahorse commented on css/style.css
> +  …
Я это взял из статьи https://htmlacademy.ru/blog/boost/frontend/short-12 , думал это универсальный шаблон на специально на все случаи жизни.

2020-10-01 12:13 UTC, Imonahorse commented on css/style.css
> +.footer-main-menu {}
Заполнил

2020-10-01 12:14 UTC, Imonahorse commented on index.html
> +          <form action="" method="GET">
+

2020-10-01 12:30 UTC, Shramkoweb commented on css/style.css
> +  …
Класс правильный, я имел ввиду эти точки https://tppr.me/2X07H что это за точки?

2020-10-01 12:44 UTC, Imonahorse commented on css/style.css
> +  …
Механический копипаст, удалено

2020-10-01 12:56 UTC, Shramkoweb requested changes

2020-10-01 12:56 UTC, Shramkoweb commented on css/style.css
> +.logo-position {
Зачем этот класс? Может его можно вынести куда то к уже имеющемося?

2020-10-01 12:56 UTC, Shramkoweb commented on css/style.css
> +  display: flex;
Так флекс или блок?

2020-10-01 12:56 UTC, Shramkoweb commented on css/style.css
> +  height: 42px;
min-h

2020-10-01 12:56 UTC, Shramkoweb commented on css/style.css
> +  height: 71px;
min-h ?

2020-10-01 12:56 UTC, Shramkoweb commented on css/style.css
> +  display: flex;
??

2020-10-01 12:56 UTC, Shramkoweb commented on css/style.css
> +  height: 45px;
min-h?

2020-10-01 12:56 UTC, Shramkoweb commented on css/style.css
> +  display: flex;
??

2020-10-01 12:56 UTC, Shramkoweb commented on css/style.css
> +  display: flex;
?

2020-10-01 12:56 UTC, Shramkoweb commented on css/style.css
>    height: 38px;
Перепроверь везде где height и есть текстовый контент, что можно обойтись min-h

2020-10-01 12:56 UTC, Shramkoweb commented on css/style.css
> +  display: flex;
?

2020-10-01 12:56 UTC, Shramkoweb commented on css/style.css
> +  display: flex;
?

2020-10-01 12:56 UTC, Shramkoweb commented on css/style.css
> +}
???

2020-10-01 13:05 UTC, Imonahorse commented on css/style.css
>    height: 38px;
А если нет текстового, например обертка в которой кнопки меню посредине, тоже min-h или можно просто height?

2020-10-01 13:22 UTC, Shramkoweb commented on css/style.css
>    height: 38px;
Везде где можно - лучше min-h.
Например с кнопками их может стать больше чем сейчас, и из-за жесткой высоты контент выпадет

2020-10-01 15:10 UTC, merged